#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get -y install nginx
ufw allow "Nginx HTTP"
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"
NGINX_CONFIG="/etc/nginx/sites-available/default"
cp "$NGINX_CONFIG" "${NGINX_CONFIG}_backup"
REDIRECT_RULE="location /redirect_me { return 301 $REDIRECT_URL; }"
sed -i "s|location \/ {|$REDIRECT_RULE|" "$NGINX_CONFIG"
service nginx restart
