#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server 254938-web-01 52.91.150.164 check
    server 254938-web-02 18.204.16.72 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
