#!/usr/bin/env bash
# Install and configure HAProxy

sudo apt-get -y update
sudo apt-get install -y haproxy

server_config=\
"
frontend mark-front
    bind *:80
    mode http
    default_backend mark-back
backend mark-back
    balance roundrobin
    server 112086-web-01 52.91.150.164:80 check
    server 112086-web-02 18.204.16.72:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
