#!/usr/bin/env bash
#script that loops from 1 to 10, 4th iteration displays bad luck 8th iteration displays goodluck, best school for the rest

n=1
while [ $n -le 10 ]
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n+1))
done
